[tool]
id = "com.thelightphone.reflect"
label = "Reflect"
versionCode = 6
versionName = "2.0.0"
serverPackage = "com.lightos"
permissions = ["android.permission.RECORD_AUDIO"]
orientation = "portrait"
# change if you run this on the emulator!
# serverPackage = "com.thelightphone.sdk.emulator"
